// NOTE: This file will be auto-generated by FlutterFire CLI
// Run: flutterfire configure
// For now, this is a placeholder. Replace with actual Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTuAUomoVFT_mHVDkL14S1iwfUSR8kLFg',
    appId: '1:9143554156:android:fe49563b766384ea1e0849',
    messagingSenderId: '9143554156',
    projectId: 'tattinkapp',
    storageBucket: 'tattinkapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWa38yCMYv9GRrj5_SPdGgmSYM55BdYBU',
    appId: '1:9143554156:ios:c32fc10d7b1af7901e0849',
    messagingSenderId: '9143554156',
    projectId: 'tattinkapp',
    storageBucket: 'tattinkapp.firebasestorage.app',
    iosBundleId: 'com.tattink.tattinkApp',
  );
}

